[project]
name = "elia-hackaton"
version = "0.1.0"
description = ""
authors = [
    {name = "Marco",email = "marco@mdigennaro.net"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pep8 (>=1.7.1,<2.0.0)"
]

[tool.poetry]
packages = [{include = "elia_hackaton", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
